### ISSUE TITLE
VAEの実装

### ISSUE THREAD

**Issue by cehl-kurage** [MLShukai/PrimitiveAMI#1]
## 概要
観測のエンコーダのひとつとしてVAEを実装する

## 背景と目的
PrimitiveAMIは観測を状態表現へとエンコードする必要があり，そのためのコンポーネントの候補がVAEである．
目的はVAEの具体的な実装を提案すること．

## 提案内容
基本的には["Large Scale Study of..."の実装](https://github.com/openai/large-scale-curiosity/blob/e0a698676d19307a095cd4ac1991c4e4e70e56fb/auxiliary_tasks.py#L73)を模倣して実装する．  

### VAE
全体像が見えないので，最小機能だけを実装して必要になるたびリファクタすることとしたい．

VAE_Encoder
-  `__init__(self, convnet)`
    - convnet: 画像のエンコード用(https://github.com/openai/large-scale-curiosity/blob/e0a698676d19307a095cd4ac1991c4e4e70e56fb/utils.py#L133)
    ただしconvnetは畳み込むだけ．VAE向けのflatten操作などはVAE_Encoder内で実装する．
- `forward`
    - convnet → feedforward → $\mu, \sigma$
    - `μ.shape == σ.shape`
    - returns: torch.distributions.Normal(μ, σ)

VAE_Decoder
- `__init__(self, deconvnet)`
    - deconvnet (https://github.com/openai/large-scale-curiosity/blob/e0a698676d19307a095cd4ac1991c4e4e70e56fb/utils.py#L147)
    convnetに同じ．
- `forward
    - deconvnet → feedfoward -> image
    - returns: image
 
## タスク

- [ ] 理解のすり合わせ（VAEをどう実装しているか？）
- [ ] Encoderの実装
- [ ] Encoderのテスト
- [ ] Decoderの実装
- [ ] Decoderのテスト

**Comment by Geson-anko** [comment]
@cehl-kurage 中身は一旦どうでもいいので一回抽象クラスを作るissue立ててください。
