### ISSUE TITLE
PPOTrainerの実装

### ISSUE THREAD

**Issue by Geson-anko** [MLShukai/PrimitiveAMI#57]
# タスク内容

https://www.notion.so/911e4788afab4c0798406b31c51a2500?pvs=4#e9f0595b14be483383f3f39fc11e3d60  
PPOLitModule, TrajectoryDataCollectorを用いて学習を行う

### 達成条件

- [x] 単純なテストを通貨する

### 関連PR
https://github.com/MLShukai/PrimitiveAMI/pull/71

**Comment by myxyy** [comment]
マージしましたのでCloseします
